//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreUI.Controls
{


    public partial class BookRow
    {

        /// <summary>
        /// BookRowElement7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BookStoreUI.Controls.Element.BookRowElement BookRowElement7;

        /// <summary>
        /// BookRowElement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BookStoreUI.Controls.Element.BookRowElement BookRowElement;

        /// <summary>
        /// BookRowElement1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BookStoreUI.Controls.Element.BookRowElement BookRowElement1;

        /// <summary>
        /// BookRowElement2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BookStoreUI.Controls.Element.BookRowElement BookRowElement2;

        /// <summary>
        /// BookRowElement3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BookStoreUI.Controls.Element.BookRowElement BookRowElement3;

        /// <summary>
        /// BookRowElement4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BookStoreUI.Controls.Element.BookRowElement BookRowElement4;

        /// <summary>
        /// BookRowElement5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BookStoreUI.Controls.Element.BookRowElement BookRowElement5;
    }
}
